export const MOCK_ACTIVITIES = [
  {
    id: "act-1",
    title: "Geeta-Hriday Book Re-publication",
    description: "Re-published Sane Guruji's classic book 'Geeta-Hriday' to promote thoughts of empathy and selfless love. Special distribution events were conducted in Sattari and neighboring areas to light up humanitarian values in society.",
    imageUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80",
    category: "Education",
    date: "2026-05-15",
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2026-05-15T10:00:00Z").toISOString(),
    updatedAt: new Date("2026-05-15T10:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "act-2",
    title: "School Study Posters Distribution",
    description: "Distributed study technique and educational posters across primary Government schools in Goa. Conducted interactive sessions with students to encourage joyful learning and mental stress reduction.",
    imageUrl: "https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80",
    category: "Education",
    date: "2026-06-01",
    status: "approved",
    isPublished: true,
    createdBy: "mock-admin-uid",
    createdByName: "Volunteer Admin",
    createdAt: new Date("2026-06-01T11:30:00Z").toISOString(),
    updatedAt: new Date("2026-06-01T11:30:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "act-3",
    title: "Community Lecture on Stress Management",
    description: "Organized a guidance lecture with invited expertise to discuss stress relief, ideal lifestyles, and respect for elderly members in families. Attended by over 120 community participants.",
    imageUrl: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80",
    category: "Awareness",
    date: "2026-06-05",
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2026-06-05T09:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-05T09:00:00Z").toISOString(),
    pendingChanges: null
  }
];

export const MOCK_PROJECTS = [
  {
    id: "proj-1",
    title: "वयात येताना Adolescent Residential Camp",
    description: "A comprehensive residential camp designed for boys and girls in the age group of 13 to 21 years. Focused on physical transition changes, leadership qualities, stress relief, and moral values.",
    imageUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80",
    category: "Rehabilitation",
    status: "Ongoing",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-10T09:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-10T09:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "proj-2",
    title: "Lokasahity Sammelan",
    description: "Organizing state folk-literature conferences to enlighten students and teachers on local heritage, folklore, and cultural roots of Goa.",
    imageUrl: "https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=800&q=80",
    category: "Education",
    status: "Ongoing",
    isPublished: true,
    createdBy: "mock-admin-uid",
    createdByName: "Volunteer Admin",
    createdAt: new Date("2025-03-15T09:00:00Z").toISOString(),
    updatedAt: new Date("2025-03-15T09:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "proj-3",
    title: "Prerna Project for Teenagers",
    description: "Welfare program targeting personality development, women's empowerment, advanced camps, and providing counselling on substance abuse and superstitions.",
    imageUrl: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=800&q=80",
    category: "Women Empowerment",
    status: "Completed",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2024-06-20T09:00:00Z").toISOString(),
    updatedAt: new Date("2024-06-20T09:00:00Z").toISOString(),
    pendingChanges: null
  }
];

export const MOCK_ARTICLES = [
  {
    id: "art-1",
    title: "Swami Vivekananda's Teachings on Human Service",
    excerpt: "Exploring Swami Vivekananda's core philosophy that 'Service to humanity is service to God', and its impact on modern community welfare.",
    body: "Swami Vivekananda strongly believed that true religion lies in character and selfless service. He famously wrote, 'I am the servant of that God, whom the ignorant call Man.' True education and social welfare must empower the individual to stand on their own feet, cultivating both mental strength and deep empathy for others.\n\nAt our society, we try to incorporate this philosophy by focusing not just on academic tutoring, but on vocational skills, ethical values, and self-reliance. Our study circles are structured to foster character development, empathy, and active community participation among students.",
    imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80",
    category: "Education",
    date: "2026-05-12",
    author: "President",
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2026-05-12T10:00:00Z").toISOString(),
    updatedAt: new Date("2026-05-12T10:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "art-2",
    title: "Eradicating Superstitions Regarding Disabled Children",
    excerpt: "An look into how medical camps and community awareness can dispel age-old misconceptions and bring rehabilitation to special children.",
    body: "Historically, disabilities in rural settings have been met with social superstitions rather than scientific treatments. Vivekananda Prerna Society works actively in Goa to dispel these beliefs by holding assessments, physiotherapy camps, and providing counselling to parents. By creating a compassionate support network, we ensure every child has the opportunity to live with confidence and respect.",
    imageUrl: "https://images.unsplash.com/photo-1508847154043-be12a62861c1?auto=format&fit=crop&w=800&q=80",
    category: "Rehabilitation",
    date: "2026-05-28",
    author: "Siddesh Gawas",
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2026-05-28T09:00:00Z").toISOString(),
    updatedAt: new Date("2026-05-28T09:00:00Z").toISOString(),
    pendingChanges: null
  }
];

export const MOCK_TEAM = [
  {
    id: "team-1",
    name: "President",
    designation: "",
    category: "Founders",
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80",
    bio: "Dedicated to children's social development, community welfare, and educational programs.",
    order: 1,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-2",
    name: "Suryakant Gaonkar",
    designation: "Vice President",
    category: "Founders",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
    bio: "Handicrafts Artist and Environmentalist. Organizes natural disaster support services and youth campaigns.",
    order: 2,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-3",
    name: "Secretary",
    designation: "",
    category: "Core Team",
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80",
    bio: "Leading primary student education projects and interactive learning campaigns.",
    order: 3,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-4",
    name: "Swapnil Volvoikar",
    designation: "Joint Secretary",
    category: "Core Team",
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80",
    bio: "Business entrepreneur. Directing logistics and layout management for events and camps.",
    order: 4,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-5",
    name: "Siddesh Gawas",
    designation: "Treasurer",
    category: "Core Team",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&q=80",
    bio: "Special Educator. Overlooks physical and mental rehabilitation camp operations and accounts.",
    order: 5,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-6",
    name: "Rashmita Rajendra Satodkar",
    designation: "Joint Treasurer",
    category: "Core Team",
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80",
    bio: "Teacher Grade-I. Devoted to managing audits and teenage development camp accounts.",
    order: 6,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-7",
    name: "Samruddhi Kerkar",
    designation: "Member",
    category: "Members",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    bio: "Artist. Spreading art education and creative training for rural and special children.",
    order: 7,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-8",
    name: "Gautami Gawas",
    designation: "Member",
    category: "Members",
    imageUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80",
    bio: "School teacher. Directing children study circles and joyful learning initiatives.",
    order: 8,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  },
  {
    id: "team-9",
    name: "Dr. Varad Sabins",
    designation: "Member",
    category: "Members",
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=800&q=80",
    bio: "Medical advisor. Designing and supporting local medical campaigns and pediatric health walks.",
    order: 9,
    status: "approved",
    isPublished: true,
    createdBy: "mock-super-admin-uid",
    createdByName: "Super Admin",
    createdAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2025-01-01T00:00:00Z").toISOString(),
    pendingChanges: null
  }
];
